version: "3"

services:
  devops:
    container_name: devops_app_python

    build: .
    image: birdi7/devops
    ports:
      - "5000:5000"
    volumes:
      - /tmp:/tmp
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

#    doesn't work on macos, so I used volume with log file
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "10"
#        tag: "{{.ImageName}}|{{.Name}}"
#
#
