repos:
- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
    - id: black
      language_version: python3.7
      files: src
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: requirements-txt-fixer

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: ["--config=setup.cfg"]

- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
    - id: isort
      args: ["--profile", "black", "--atomic"]

# I wasn't able to fix MD029 on my files, so commented out.
# The configuration is fine
# - repo: https://github.com/markdownlint/markdownlint
#   rev: v0.11.0
#   hooks:
#     - id: markdownlint

- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.1
  hooks:
    - id: dockerfile_lint
