version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
      - /tmp:/tmp
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - loki

    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
