version: "2.4"

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
    tag: "{{.ImageName}}|{{.Name}}"
  driver: json-file

x-resources:
  &default-resource-limits
  cpus: 0.5
  mem_limit: 200M

x-common:
  &common-params
  logging: *default-logging
  networks:
    - loki
  <<: *default-resource-limits

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    <<: *common-params


  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
      - /tmp:/tmp
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yml
    <<: *common-params

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    <<: *common-params

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

    <<: *common-params


volumes:
  grafana-storage:
